apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-app-sm
  namespace: default
  labels:
    prometheus-monitored: "true"
spec:
  endpoints:
    - interval: 10s
      port: web
      path: /metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      prometheus-monitored: "true"
